CircleCI-Public/server-scripts

- migrate/restore.sh
Problem:
after the migration the bot token will be out of sync between the databases and the k8s resources
Solution:
Grab the previously run job definition, and re-run it to sync the bot token across the application.
> [SERVER-1002] re-run the bottoken job after the database migrations

- migrate/2.19-compress.sh
- migrate/2.19-export.sh
- migrate/2.19-key.sh
- migrate/2.19-preflight.sh
- migrate/2.19-vault.sh
- migrate/3.0-preflight.sh
- migrate/3.0-restore.sh
- migrate/3.0-scale.sh
- migrate/README.md
- migrate/migrate.sh
SERVER-1288
Some customers may only have Postgres externalized
and need help migrating. DCEs would have to do the
process manually without this script.
> Allow migrations to skip postgres or mongo or vault

- migrate/3.0-restore.sh
- migrate/migrate.sh
Open connections to postgres are causing duplicate records in the `build_queue_migrations` table on the `circle` database in postgres. We restart postgres during the restore process to kill any open connections
https://circleci.atlassian.net/browse/SERVER-1349
> [server-1349] restarting postgres during restore process

- migrate/migrate.sh
migrate.sh bombs out late in the process if run as non-root on a base Ubuntu Focal instance because jq is not installed. Rather than wait 30 minutes or more for the script to shutdown 2.19 and export all the data before failing, check that jq is installed before doing anything.
> Add jq check to migrate.sh as a pre flight check.

- kots-exporter/kots-exporter.sh
[SERVER-2031](https://circleci.atlassian.net/browse/SERVER-2031)
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: PodDisruptionBudget "nomad-server" in namespace "xxxxx" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "circleci-server"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "xxxx"
```
* Added `pdb` resource in the list
> SERVER-2031 | Added pdb resource 

- kots-exporter/kots-exporter.sh
- kots-exporter/templates/circle-migrator.yaml
- [SERVER-2003](https://circleci.atlassian.net/browse/SERVER-2003)
We can safely remove the migration job once the `kubectl wait` command completes successfully.
Test a successful (no-op) migration:
```
./kots-exporter.sh -a circleci-server -n circleci -f flyway                                                                                                                                                                                            ...
############ RUNNING FLYWAY DB MIGRATION JOB ################
Checking if job/circle-migrator already ran -
Fetching values from pod/frontend-6758678865-zlfm5 pod
Creating job/circle-migrator -
job.batch/circle-migrator created
Waiting job/circle-migrator to complete -
job.batch/circle-migrator …
```
> [SERVER-2003] Remove migration job once it has completed

- kots-exporter/kots-exporter.sh
[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)
* Script will abort if job `circle-migrator` is not finished in 300 secs
* Added instructions to follow if job `circle-migrator` is not finished in 300 secs
* Change `error_exit` to `echo`
* Added `check_postreq` function to check k8s namespace and helm release
> SERVER-2047 | added job deletion step

- kots-exporter/kots-exporter.sh
The migration script outputs telegraf's config in base64
We should decode this so that a customer can easily update it
Telegraf config is now decoded in values.yaml
> server-2020/decrypt-telegraf-config

- .github/CODEOWNERS
- README.md
- migrate-3-to-4/README.md
- migrate-3-to-4/bottoken.sh
- migrate-3-to-4/exporter.sh
- migrate-3-to-4/key.sh
- migrate-3-to-4/mongo.sh
- migrate-3-to-4/postgres.sh
- migrate-3-to-4/preflight.sh
- migrate-3-to-4/restore.sh
- migrate-3-to-4/scale.sh
- migrate-3-to-4/temp-vault-pod.yml
- migrate-3-to-4/templates/circle-migrator.yaml
- migrate-3-to-4/vault-pvc.yml
- migrate-3-to-4/vault.sh
Sometimes KOTS does not have the expected helm application installed.  In this case we need to do the migration to 4.0 a different way.
Migrate from 3.4 to 4.0 with database migrations between 2 separate installations.
Very little of this is net new work.  It is mostly copy pasted from the 2.19 migration scripts.
I prioritized minimizing changes over beautiful and concise code.  Also, this is currently to solve a problem for one customer and is unlikely to see use beyond that.
To make your review easier, consider reviewing each commit individually, or comparing the files to what they were copied from:
migrate-3-to-4/exporter.sh - kots-exporter/kots-exporter.sh
migrate-3-to-4/bottoken.sh - migrate/3.0-bottoken.sh
migrate-3-to-4/key.sh - …
> [SERVER-2273] Migrate 3.4 to a new 4.0 instance 

- kots-exporter/kots-exporter.sh
I was unable to run the kots-exporter.sh script when my Helm app is installed in a different k8s namespace other than circleci-server (default).
I see the following error:
```
------->> Error: Helm release circleci-server does not exist.
```
This occurred even when specifying the namespace via the `-n <namespace>` option.
This fix ensures the `helm list` command looks up the specified namespace.
I tested this worked to the point of the following outputs:
```
$ ./kots-exporter.sh
Script Path: /Users/kelvin/personal/server-scripts/kots-exporter
############ CHECKING REQUIRED ARGUMENTS ################
KOTS admin namespace (circleci-server): circleci
License Key String: jdslakldklk;ad
############ SET DEFAULT VALUES ################
############ …
```
> fix: pass namespace when listing Helm releases

- kots-exporter/kots-exporter.sh
When the k8s namespace has more than 1 Helm app installed, the kots-exporter will fail since the following command will return multilines.
```console
$ helm list -n circleci -o yaml | yq '.[].name'
circleci-server
helloworld
```
:white_check_mark: **Fix** 
I modified the yq command, using `yq` operators, to look up the list of Helm apps by name.
This fixes the case where the k8s namespace contains >1 Helm app.
- `-e` for `--exit-status`
- `contains` to look up an array: https://mikefarah.gitbook.io/yq/operators/contains
- `strenv` to load the `$slug` env var: https://mikefarah.gitbook.io/yq/operators/env-variable-operators#read-boolean-environment-variable-as-a-string
```console
$ helm list -n circleci -o yaml | yq '.[].name'
circleci-server
helloworld
```
```console
$ …
```
> fix: look up app slug in list of Helm apps

- README.md
- vault-to-tink/README.md
- vault-to-tink/export-contexts.sh
- vault-to-tink/import-contexts.sh
The export script leaves very sensitive data behind, and the migration will incur some downtime for jobs that use contexts, but the risk is minimal. With that said, please make a backup first anyway.
WANTED: A way to dry-run at least the export (where we'd maybe export the names in contexts and not the values)
Our Vault story is not great so we're moving to Tink instead.
SERVER-2432
Introducing: a script to move your installation from Vault to Tink!
> feat: Vault to Tink migration script

- support/support-bundle.yaml
Given recent investigations for a Server customer re: RabbitMQ queue sizes increasing, I noted we do ask customers to run the following on their k8s cluster:
```console
$ kubectl -n <namespace> exec rabbitmq-0 -- rabbitmqctl list_queues
```
I think it thus may be good to also include this information as part of the support bundle.
I added this command to be part of the data collectable for our support bundle manifest.
I think this command is not expensive to run, so it shouldn't be "taxing" on the k8s cluster 🤞 
Verified on my Server 4.1.x instance:
> feat: collect rabbitmq queue info

- support/support-bundle.yaml
* Duplicate logs folder are increasing the size of support bundle if there are multiple replicas for each service 
* deleted the logs folder "application", "data" and "nomad" as all the logs are available under cluster-resources/pods/logs/ folder
> SERVER-2470 | remove dup logs

- kots-exporter/README.md
- migrate-3-to-4/README.md
- Noticed a few typos in the `README.md` files for [kots-exporter](https://github.com/CircleCI-Public/server-scripts/tree/main/kots-exporter#server-kots-exportergs) and the [migrate-3-to-4](https://github.com/CircleCI-Public/server-scripts/tree/main/migrate-3-to-4#prequsites) section of the `migrate-3-to-4` folder. 
- Added `-n <circle-app-namespace>` to the create `regcred` secret command in the [kots-exporter](https://github.com/CircleCI-Public/server-scripts/tree/main/kots-exporter) README page for more clarity. We have had a couple of instances where customers ran it in their default namespace without the `-n` reference, resulting in a few extra steps that could have been avoided. 
- Minor typo fixes and README changes. No changes to …
> Typo fixes in kots-exporter and migratre-3-to-4 README docs

- migrate-3-to-4/exporter.sh
- migrate-3-to-4/mongo.sh
With our installation, our mongo db was 17GB on disk, and 52GB in the export format.  Our data volume was expanded to 100GB previously, but there was no way the export would have fit into /tmp (only 50GB with 17GB in use).
This fix just uses the data volume which (in our case) already had the space available, but there is probably a better way to create a large temporary volume for the backup process.
This code got us to 4.x. 😃
> migrate-3-to-4: use mongo data volume for backup

- migrate-3-to-4/README.md
- Added prerequisites for the `migrate-3-to-4` script. I am aware that we might archive these soon but just want to make sure that these are captured so we don't forget some of the important steps required if we ever revisit these future. 
- Scaling down the application pods seems to be an important step for customers run the export script against > 50GB databases. 
- Encountered these during a live upgrade with a customer.
> Add note regarding prerequisites and scaling down pods

- vault-to-tink/import-contexts.sh
The account context ID of `6ecee9e4-1c95-4e0d-8af3-5c57c35e84c8` is hardcoded. It will never have an associated org, therefore we can just hardcode a name for it and move on.
> fix: Proceed with account context

- vault-to-tink/import-contexts.sh
user reported encountering an error while attempting to import multiple context variables using the import-script. The error message indicates a problem with the URL formatting, preventing the successful import of the contexts.
The issue stems from how multiple contexts are being handled in the script. When multiple contexts are present, they are not processed individually. Instead, they are read together, causing the URL to become malformed with concatenated context names.
```
++ curl -sS -o response.txt -w '%{http_code}' --request PUT --url 'https://<hostname>/api/v2/context/<context_id>/environment-variable/GITHUB_TOKEN
CIRCLE_TOKEN' --header 'Circle-Token: SECRET' --header 'Content-Type: application/json' --data '{"value":"GITHUB_TOKEN_VALUE"
"CCI_TOKEN_VALUE"}'
Org …
```
> vault-to-tink/import-contexts.sh URL Error When Importing Multiple Contexts

- support/support-bundle.yaml
With k8s support bundle, we can fetch the deployed server version in directory `server-version`
> ONPREM-1485 | Fetch server version in support bundle
