CircleCI-Public/server-scripts

.circleci/config.yml

This adds a simple CI job with shellcheck and Slack notifications for
the repo

Add simple CI with shellcheck

---

support/README.md
support/support-bundle.yaml

This PR adds in a support bundle for server debugging.

Adding Support Bundle

---

.gitignore
kots-exporter/README.md
kots-exporter/kots-exporter.sh
kots-exporter/templates/circle-migrator.yaml

Moving Exporter code from Internal Repo to External.
Commit - [f30710f](https://github.com/circleci/server-kots-exporter/commit/f30710f69a6af048ca421a1f9bee5f1d1fb61268) 

server-1927| moving code from internal repo to external

---

.gitignore
kots-exporter/kots-exporter.sh

* Err 1
```
Error: UPGRADE FAILED: error validating "": error validating data: [unknown object type "nil" in Secret.stringData.ec2AccessKey, unknown object type "nil" in Secret.stringData.ec2SecretKey]
```
* Err 2
```
Error: UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.stringData.mongodb-password
```
[SERVER-2011](https://circleci.atlassian.net/browse/SERVER-2011)
* Added a randomly generated password for `mongodb.password`
* Cleaned up `null`

server-2011 | added mongodb password & cleanup null

---

kots-exporter/kots-exporter.sh

language fix

---

kots-exporter/kots-exporter.sh

https://circleci.atlassian.net/browse/SERVER-1999
helm-values.yaml when generated does not include the registry to pull images from
fixed it

helm reg included in helm-values output

---

kots-exporter/kots-exporter.sh
kots-exporter/templates/circle-migrator.yaml

[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)
* Added TTL for migrator job
* Increased wait to 10 mins
* Deleted the Job deletion commands

SERVER-2047 | added ttlSecondsAfterFinished in job

---

kots-exporter/kots-exporter.sh

[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)
* Defaulted release-name as `circleci-server`

server-2047 | defaulted release name

---

kots-exporter/kots-exporter.sh

[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)
* Auto execution of Postgres commands if using Internal Postgres
* ~~Re-creating the postgres password secret as a precautionary step~~ 
* Cleaned-Up trailing whitespaces

server-2047 | simplified postgres migration

---

kots-exporter/kots-exporter.sh

* CI is failing
* Added a missing `fi`

no-jira | fix shellcheck

---

support/support-bundle.yaml

[SERVER-2100](https://circleci.atlassian.net/browse/SERVER-2100)
* Added nomad status in support bundle

server-2100 | added nomad status in support bundle

---

kots-exporter/kots-exporter.sh

shell-check-fix | fix shellcheck

---

support/support-bundle.yaml

[SERVER-2101](https://circleci.atlassian.net/browse/SERVER-2101)
* Added PVC size calculation (`df`) 
:question: **Documentation**

server-2101 | added pvc size calc

---

README.md

server-2042 | add root readme file

---

migrate-3-to-4/bottoken.sh
migrate-3-to-4/exporter.sh
migrate-3-to-4/postgres.sh

Multiple errors while running the migrate-3-to-4 scripts.
Adding namespaces and adjusting sed arguments
Tested with attempted migration.

Fix multiple errors from migrate-3-to-4 scripts

---

support/support-bundle.yaml

This reverts commit 03802d9625eea62330642552fc7cd52970a2d5e5.

Revert "SERVER-2470 | remove dup logs (#48)"

---

kots-exporter/kots-exporter.sh

[SERVER-2528](https://circleci.atlassian.net/browse/SERVER-2528)
* enabled aliases for helm and kubectl with verbose log if `-v` flag is set
[SERVER-2528]: https://circleci.atlassian.net/browse/SERVER-2528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SERVER-2528 | added -v flag for verbose log

---

upgrade-mongo-to-4.4/README.md
upgrade-mongo-to-4.4/upgrade-mongo-image.sh

https://circleci.atlassian.net/browse/SERVER-2520
automates the mongoDB image upgrade process

Server 2520/upgrade mongo script

---

vault-to-tink/README.md

*No Jira* 
Updated Readme for Java dependency for `tinkey` command to work

chore-add | added java dependency

---

vault-to-tink/import-contexts.sh

* Script check for Org name and print it while processing the contexts
* If Org name does not exists (Org no more exists), contexts are not processed
* Generate another input file with failed contexts import
* Generate a report at end. 

ONPREM-1683 | Added retry logic in Contexts import script
